Repository anubizz-dev/AAD__website, pull requests merged in 2024-06, with the labels that each got.

#6 Service cards UI fixed
  resources/views/index.blade.php
  tailwind.config.js
Labels: UI

#7 Added .env.example
  .env.example
Labels: bug

#9 Added sending contact us messages
  .env.example
  app/Http/Controllers/IndexController.php
  app/Mail/InquiryEmail.php
  resources/views/emails/inquiry.blade.php
  resources/views/index.blade.php
  routes/web.php
Labels: enhancement

#10 env example cleanup
  .env.example
Labels: bug

#12 -added favicon and carousel button
  public/img/AADfavicon.png
  resources/views/index.blade.php
Labels: UI

#15 Hostgator Manual
  Hostgator.md
Labels: documentation
